### PR TITLE
Feature netmap

### PR DESCRIPTION
**Pull request by fklassen**
netmap enhancement as per http://info.iet.unipi.it/~luigi/netmap/

### CODE REVIEW

**Comment by synfinatic** [comment]
Hey Fred,

So the patch looks quite good!  One question since I don't have any compatible hardware/OS handy, but looks like if tcpreplay is compiled with netmap support, it will try to use it and if that fails, then fall back to the normal method.  I was reading your docs and sounds like netmap effectively disconnects the TCP/IP stack from that interface while tcpreplay is running.  I'm wondering if it makes sense to make enabling netmap a runtime option?

Anyways, I won't bother to hold up this merge request for adding a runtime option, but I am curious about the if netmap is supported on BSD systems with BPF.  If so, then a tweak here makes sense:

https://github.com/appneta/tcpreplay/commit/1d958ece6baa687ccec5940ea04178722e4b0b19#commitcomment-4687884

**Comment by fklassen** [comment]
Hi Aaron.

I agree that since netmap is potentially disruptive to the IP stack it should be a runtime option. I'll get on it.

As for merge, this is a fairly major change and you may feel more comfortable just pulling the branch into your repository and let's make sure it is fairly complete before you merge to master. You could also close the pull request and we can collaborate appneta/tcpreplay. I plan to do 4 or so features and enhancements, which will match work I did in 3.5beta1 and has been in use by our QA team for the last 8 months. You may want me to I keep the work on my side of the fence until you are happy with it, then I can do another pull request. It's up to you.

**Comment by synfinatic** [comment]
4.0 is considered unstable, so I won't even worry if the run time option isn't there from day one.   So if you want to break it up into multiple merge requests that's fine.  Might make sense to do that in conjunction with ticket #96 anyways.

I'd rather not do development in two different repos, so if you wanted to collaborate, I'd just add you as a developer to synfinatic/tcpreplay.  I've seen enough of your code to the point I'm comfortable doing that.

**Comment by fklassen** [comment]
I didn't know that contributing directly in synfinatic/tcpreplay was an option. Certainly I don't have permissions to accept the pull requests to bring the 2 branches I created into your repo. Maybe after you accept the pull requests I can work on them in your repo and merge to master.

Thanks for the vote of confidence. I have been working many years on development of wire-rate apps with minimal CPU load. Our kernel enhancements even work on ARM and PPC. Someday we may submit some of our proprietary appliance code to open source. We developed it before I ever saw netmap and  has some key features not available anywhere else.

**Comment by synfinatic** [comment]
Just granted you access.  I'll review the requests tonight.

**Comment by fklassen** [comment]
As discussed, netmap injector is an option. Here is an example execution:

```
# bin4.0/tcpreplay --preload-pcap --intf1=eth7 --mbps=0 bosTap.pcap 
File Cache is enabled
Actual: 791615 packets (355417784 bytes) sent in 0.50 seconds.
Rated: 710835584.0 Bps, 5686.68 Mbps, 1583230.00 pps
Statistics for network device: eth7
    Attempted packets:         791615
    Successful packets:        791615
    Failed packets:            0
    Retried packets (ENOBUFS): 0
    Retried packets (EAGAIN):  0

# bin4.0/tcpreplay --preload-pcap --intf1=eth7 --netmap --mbps=0 bosTap.pcap 
Switching network driver to netmap bypass mode... done!
File Cache is enabled
Actual: 791615 packets (355417784 bytes) sent in 0.30 seconds.
Rated: 1184725888.0 Bps, 9477.81 Mbps, 2638716.75 pps
Statistics for network device: eth7
    Attempted packets:         791615
    Successful packets:        791615
    Failed packets:            0
    Retried packets (ENOBUFS): 0
    Retried packets (EAGAIN):  0
Switching network driver to normal mode... done!
```

Note that it takes about 4 seconds to switch to/from netmap mode. There is an interface reset involved. Therefore the second run has additional messages that let the user know that they should be patient.

**Comment by fklassen** [comment]
Merged into appneta/tcpreplay

**Pull request closed without merging**
